---
- name: install docker-py workaround
  pip: name=docker-py
  
- name: start webserver container
  docker:
    name: "{{ container_name }}"
    image: antonienko/nginx-php-fpm:v0.4
    state: reloaded
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ local_web_folder }}:/var/www"
      - "{{ nginx_config_folder}}:/etc/nginx/sites-enabled"
      - "{{ certs_folder}}:/etc/nginx/ssl"
    links: "{{linked_containers}}"
    env: "{{env_vars}}"
